name: simple-blas-ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  bench:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libopenblas-dev

      - name: Run test
        run: make test

      - name: Build bench binary
        run: make bench

      - name: Run benchmark suite
        env:
          SIMPLE_SGEMM_THREADS: 2
          OPENBLAS_NUM_THREADS: 2
          OMP_NUM_THREADS: 2
        run: make run
